
services:

  # @see https://hub.docker.com/_/httpd
  apache:
    container_name: ${COMPOSE_PROJECT_NAME}-apache
    build: './apache/'
    ports:
      - 8000:80
      - 443:443
    volumes:
      - ./web/public_html:/var/www/html
    depends_on:
      - php-fpm
      - db
    # networks:
    #   - frontend
    #   - backend

  # @see https://hub.docker.com/_/mariadb
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: mariadb:10.5
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      # - ./db/data:/var/lib/mysql    
      - db-data:/var/lib/mysql
      # - ./db/import:/docker-entrypoint-initdb.d # Put .sql files here to auto-import when the container is first built
    # networks:
    #   - backend

  # @see https://thriveread.com/docker-apache-httpd-with-php-fpm-and-mysql/
  php-fpm:
    container_name: ${COMPOSE_PROJECT_NAME}-php-fpm
    build: 
      context: './php-fpm/'
      args:
        SMTP_USER: ${SMTP_USER}
        SMTP_PASSWORD: ${SMTP_PASSWORD}
    user: 1000:1000
    environment:
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_DB_HOST: ${MARIADB_HOST}
      # PHP_MEMORY_LIMIT: 256M
    volumes:
      - ./web/public_html:/var/www/html
    depends_on:
      - db
    # networks:
    #   - backend

  # @see https://hub.docker.com/_/phpmyadmin
  phpmyadmin:
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: ${MARIADB_HOST}
      UPLOAD_LIMIT: '128M'
    # networks:
    #   - backend

  # @see https://hub.docker.com/_/wordpress/
  wp-cli:
    container_name: ${COMPOSE_PROJECT_NAME}-cli
    image: wordpress:cli
    # build: 
    #   context: './wp-cli/'
    #   args:
    #     MARIADB_NAME: ${MARIADB_DATABASE}
    #     MARIADB_HOST: ${MARIADB_HOST}
    #     MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    user: 1000:1000
    command: tail -f /dev/null # Keep the container running rather than exiting after initialization @see https://mklasen.com/adding-and-using-wp-cli-in-a-docker-compose-setup/
    environment:
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_DB_HOST: ${MARIADB_HOST}
    volumes:
      - ./web/public_html:/var/www/html/ #TODO need to check this
      # - ./wp-content:/var/www/html/public_html/wp-content #TODO need to check this
      - ./backups:/var/www/backups
      # - ./db/import:/var/www/db-import
    depends_on:
      - db
      # - apache

volumes:
  db-data:
  # web:

# networks:
#   backend:
#   frontend: