
services:

  # @see https://hub.docker.com/_/httpd
  apache:
    container_name: ${COMPOSE_PROJECT_NAME}-apache
    build: './apache/'
    ports:
      - 8889:80
      - 443:443
    volumes:
      - wp-content:/var/www/html
    depends_on:
      - wordpress
      - db
    # networks:
    #   - frontend
    #   - backend

  # @see https://hub.docker.com/_/mariadb
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: mariadb:10.5
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    # networks:
    #   - backend

  wordpress:
    container_name: ${COMPOSE_PROJECT_NAME}-wp
    image: wordpress:latest
    volumes:
      - ./wp-content:/var/www/html/wp-content
    ports:
      - 8888:80 #TODO check the port mapping
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${MARIADB_HOST}
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
    depends_on:
      - db

  # @see https://hub.docker.com/_/phpmyadmin
  phpmyadmin:
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: ${MARIADB_HOST}
      UPLOAD_LIMIT: '128M'
    # networks:
    #   - backend

  # @see https://hub.docker.com/_/wordpress/
  # wp-cli:
  #   container_name: ${COMPOSE_PROJECT_NAME}-cli
  #   image: wordpress:cli
  #   user: '33'
  #   # command: tail -f /dev/null # Keep the container running rather than exiting after initialization @see https://mklasen.com/adding-and-using-wp-cli-in-a-docker-compose-setup/
  #   command: >
  #     /bin/sh -c '
  #     sleep 10;
  #     wp core install --path="/var/www/html" --url="http://localhost:8888" --title="Local Wordpress By Docker" --admin_user=${wp_admin} --admin_password=${wp_admin_password} --admin_email=${wp_admin_email}
  #     '
  #   environment:
  #     WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
  #     WORDPRESS_DB_USER: ${MARIADB_USER}
  #     WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
  #     WORDPRESS_DB_HOST: ${MARIADB_HOST}
  #   volumes:
  #     - ./wp-content:/var/www/html/wp-content 
  #     - ./backups:/var/www/backups
  #   depends_on:
  #     - db
  #     - wordpress

volumes:
  db-data:
  wp-content:

# networks:
#   backend:
#   frontend: